lib/asciidoctor-epub3/converter.rb
lib/asciidoctor-epub3/packager.rb

Current asciidoctor-epub3 ignore `-o` `--out-file` options. This patch pass target options into packager to fix it.

Fix -o --out-file options

---

lib/asciidoctor-epub3/converter.rb

Fix error:
```
asciidoctor-epub3/lib/asciidoctor-epub3/converter.rb:320: syntax error, unexpected ']', expecting tSTRING_DEND
...class="#{'discrete', node.role].compact * ' '}">#{node.title...
```

Fix missing square brackets

---

README.adoc

The docs describe that the avatar image should be called `{username}.png` but actually only `{username}.jpg` seems to be supported. 
See:
https://github.com/asciidoctor/asciidoctor-epub3/blob/c9851d08aeee9b5b94fa9452fdb0763fcfc1ec25/lib/asciidoctor-epub3/converter.rb#L187
https://github.com/asciidoctor/asciidoctor-epub3/blob/c9851d08aeee9b5b94fa9452fdb0763fcfc1ec25/lib/asciidoctor-epub3/packager.rb#L189

Fixed file type of avatar image in docs

---

README.adoc
data/samples/sample-content.adoc
lib/asciidoctor-epub3/converter.rb
lib/asciidoctor-epub3/packager.rb

- proxy CSS in KF8 format to work around KDP removing font-related CSS
- don't include iBooks config file in KF8 format
- don't include scoped icon CSS in KF8 format

Fix how publisher fonts are handled in KF8 format

---

README.adoc

I noticed a typo in the README file and corrected it, in case anyone wanted to cut and paste the affected line of code.

Fix README typo, strong tag misspelled

---

lib/asciidoctor-epub3/converter.rb

A small change  for a TODO that needed to be done.

Open blocks keep id and classes if specified

---

lib/asciidoctor-epub3/converter.rb
lib/asciidoctor-epub3/spine_item_processor.rb

- give each document a reference to the spine items (aka other documents)
- look in spine items collection to resolve title of inter-document xref

resolves #87 automatically resolve title of reference between documents

---

lib/asciidoctor-epub3/converter.rb
lib/asciidoctor-epub3/spine_item_processor.rb

- register ID of each spine item document
- allow reftext for spine item doctitle to be specified using docreftext attribute

register chapter ID in references

---

README.adoc
data/samples/sample-book.adoc
lib/asciidoctor-epub3/converter.rb
lib/asciidoctor-epub3/spine_item_processor.rb

- generate valid ID for chapter (which is also a valid file name)
- resolve character references before generating ID
- strip single curved quote; replace &amp; with "and"
- honor idprefix and idseparator attributes when generating IDs 
- document in the README how the chapter ID is generated
- revise the Declaring the Spine section in the README
- warn if chapter use a reserved ID

resolves #46 clean auto-generated file names for chapters

---

lib/asciidoctor-epub3/converter.rb
lib/asciidoctor-epub3/spine_item_processor.rb

- use imagesdir from spine document for avatar location

resolves #2 built-in avatar location should respect imagesdir

---

lib/asciidoctor-epub3/converter.rb

- don't create back link from bibliography entry unless there's a reference to jump to

resolves #19 fix broken links in bibliography

---

lib/asciidoctor-epub3/spine_item_processor.rb

- pass overridable leveloffset attribute to spine item documents
- with a corresponding change to core, this allows a leading level-1 section title to become a doctitle

resolves #107 pass leveloffset to spine item documents

---

lib/asciidoctor-epub3/converter.rb

This fixes #112, just looked at the difference in the `html5.rb` quote converter.

assign role classes to quote block

---

data/styles/epub3.css
lib/asciidoctor-epub3/converter.rb

This uses the chapter title text as the user had it, and leaves it to the CSS to uppercase.
The current stylesheet already has `text-transform: uppercase` on the titles.
This was noted at #97. I am also trying to use a custom CSS for the chapter header that doesn't have uppercased titles.

leave it to the css to uppercase the titles

---

lib/asciidoctor-epub3/packager.rb

Fixes a small issue where I was using `url(../fonts/notoserif-regular-latin.ttf) format("truetype")` in my custom CSS and the pattern didn't match that form.

match CSS font urls

---

data/styles/epub3.css
lib/asciidoctor-epub3/converter.rb
lib/asciidoctor-epub3/packager.rb
lib/asciidoctor-epub3/spine_item_processor.rb

* enable catalog_assets option on documents in spine
* read images from catalog (i.e., references) table
* move call to add_content_images method inside add_content method
* add svg to epub properties list if an inline SVG image is detected
* set width of inline image to value of scaledwidth attribute, if specified
* if scaledwidth attribute is not specified and image is an SVG, set value to 100%
* add inline class to inline image elements
* add max-width: 100% style to all images (not just figures)
* group figure.image styles together in stylesheet

resolves #5 package inline images

---

lib/asciidoctor-epub3/converter.rb

Malformed XML prevents Calibre to display footnote properly, see
https://bugs.launchpad.net/calibre/+bug/1839490
Fixed by escaping with CDATA block.
If you prefer I can extract this as an external script instead.

Fix javascript cause malformed XML

---

Gemfile

Previous kindlegen releases are unable to install in Windows.
See https://github.com/tdtds/kindlegen/pull/33

Bump kindlegen dependency to 3.0.5

---

Gemfile

pygments.rb 1.1.2 fails if there's no find(1) on PATH (usually, Windows):
```
Errno::EACCES: Permission denied @ rb_file_s_symlink -
(vendor/pygments-main/scripts/debug_lexer.py,
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/pygments.rb-1.1.2/vendor/pygments-main/scripts/find_error.py)
An error occurred while installing pygments.rb (1.1.2), and Bundler cannot
continue.
```
This issue was fixed in pygments.rb 1.2.0: https://github.com/tmm1/pygments.rb/pull/181

Bump pygments.rb to 1.2.1

---

.travis.yml
Rakefile
asciidoctor-epub3.gemspec
spec/executable_spec.rb
spec/spec_helper.rb

If/when this gets merged, #218 needs to be adjusted to call `bundle exec rake spec`
This PR definitely goes towards resolving #11, though scope of that issue isn't clear, so I'm not sure it counts as "resolve".

Naive rspec-based testing infrastructure

---

Gemfile
README.adoc
WORKLOG.adoc
lib/asciidoctor-epub3/packager.rb

Notes to reviewers:
1. These are the first lines of Ruby code I've ever written in my life. If they're not Ruby-way, please tell me
2. I'm not sure the way I handle `-w`/`-q` is the way @mojavelinux wants it to be
3. epubcheck-ruby 4.2.2.0 was [just released](https://github.com/takahashim/epubcheck-ruby/releases/tag/v4.2.2.0). However, it detects problems in files generated by asciidoctor-epub3, so I suggest doing 4.1.1.0 -> 4.2.2.0 upgrade in a separate PR:
```
ERROR(RSC-005): ./sample-book.epub/OEBPS/asciidoctor-epub3-a-native-epub3-converter-for-asciidoc.xhtml(23,70): Error while parsing file: element "style" not allowed here; expected the element end-tag, text, element "a", "abbr", "address", "area", "article", "aside", "audio", "b", "bdi", "bdo", "blockquote", "br", "button", …
```

resolves #224 use epubcheck-ruby instead of epubcheck

---

README.adoc

asciidoctor-epub3 is not testing anything older on CI.

Change oldest supported Ruby to 2.3 in README

---

Gemfile

Commit cead09c881199388bca86dfa30df43ca2c83a175 attempted to test against asciidoctor-1.5.3 (oldest supported) on Travis.
However, unlike asciidoctor-pdf, asciidoctor-epub3 didn't have any logic for ASCIIDOCTOR_VERSION.

Handle ASCIIDOCTOR_VERSION env variable in Gemfile

---

.gitignore

This way it doesn't show up as untracked and IDEA stops suggesting to `git add` it.

Add IntelliJ IDEA config dir to .gitignore

---

spec/cli_spec.rb

This is a more consistent naming with other Asciidoctor projects.

Rename executable_spec.rb -> cli_spec.rb

---

.github/workflows/ci.yml
.github/workflows/release.yml
.travis.yml
README.adoc

This PR introduces two GitHub Actions workflows:
1. `.github/workflows/release.yml`
Publishes gem to rubygems.org when tag is pushed to git. In order for this workflow to work, repository owner needs to set up `RUBYGEMS_API_KEY` secret in GitHub repository settings.
Note that I was unable to test whether this workflow actually works because do not have permission to push to rubygems.org.
This workflow is provided just for convenience in case if complete migration to GitHub Actions is deemed good.
2. `.github/workflows/ci.yml`
This workflow builds and tests asciidoctor-epub3 on ruby 2.3-2.7 on Linux/MacOS/Windows, except 2.3 on Windows (not supported), 2.7 on Windows (waiting for sparklemotion/nokogiri#1961) and jruby on Windows (not supported).
The reason for using GitHub Actions instead …

Add GitHub Actions CI script

---

CHANGELOG.adoc
lib/asciidoctor-epub3/packager.rb
spec/cli_spec.rb

On Windows, we cannot just execute file with shebang.
Instead, invoke `ruby <file>`.
Use the same Ruby executable we're running on.

resolves #232 fix `-a ebook-validate` not working on Windows

---

CHANGELOG.adoc
asciidoctor-epub3.gemspec

This will produce a warning on ancient Asciidoc versions, but this warning is harmless:
> asciidoctor: WARNING: gem 'thread_safe' is not installed. This gem is recommended when registering custom converters.

resolves #234 drop unused dependencies: thread_safe, concurrent-ruby

---

CHANGELOG.adoc
lib/asciidoctor-epub3/converter.rb
spec/cli_spec.rb
spec/converter_spec.rb
spec/spec_helper.rb

Now asciidoctor-epub3 will just log an error when given a document that doesn't follow asciidoctor-epub3 rules
@mojavelinux I'd like your receive your approval for this

resolves #7 fix the (in)famous `undefined method `to_ios'`

---

data/samples/asciidoctor-epub3-readme.adoc
data/samples/sample-book.adoc
spec/cli_spec.rb

Windows doesn't adequately support symlinks and even though Git for Windows has experimental symlink support, it is disabled by default.
Instead of a symlink, data/samples/asciidoctor-epub3-readme.adoc is just a regular file with following contents on Windows:
../../README.adoc
So, while book does produce EPUB without errors, it doesn't contain expected contents.
----
As you can [see](https://github.com/slonopotamus/asciidoctor-epub3/runs/402381008#step:6:120), bug described in #196 does not reproduce on Windows because it is hidden by a symlink bug.

Remove symlink from sample book

---

asciidoctor-epub3.gemspec

Because Asciidoctor 1.5.3 is the oldest version we're testing against.

Require at least Asciidoctor 1.5.3 in gemspec

---

CHANGELOG.adoc
lib/asciidoctor-epub3/converter.rb

Tested using Namo Reader for Windows + Namo eBook Reader for Android.

resolves #192 remove Namo Reader font-icon quirk that produced invalid markup

---

CHANGELOG.adoc
Gemfile
asciidoctor-epub3.gemspec

With such dependency specification, [kindlegen 3.0.3 is installed on Ruby 2.3](https://github.com/slonopotamus/asciidoctor-epub3/runs/410191198?check_suite_focus=true#step:5:46) and [kindlegen 3.0.5 is installed on newer Rubies](https://github.com/slonopotamus/asciidoctor-epub3/runs/410191235?check_suite_focus=true#step:5:43).

resolves #270 make kindlegen a runtime dependency

---

Gemfile
asciidoctor-epub3.gemspec

Same as with kindlegen - without declaring dependency in gemspec, users don't get epubcheck-ruby installed when they do `gem install asciidoctor-epub3`.
epubcheck is not as critical as kindlegen, but still.

make epubcheck-ruby a runtime dependency

---

CHANGELOG.adoc
lib/asciidoctor-epub3/packager.rb

KindleGen writes warnings to stdout, so route its stdout throug log_line helper

resolves #291 log KindleGen warnings with WARNING log level

---

CHANGELOG.adoc
lib/asciidoctor-epub3/packager.rb
spec/fixtures/reproducible/book.adoc
spec/fixtures/reproducible/chapter.adoc
spec/reproducible_spec.rb
spec/spec_helper.rb

Also, respect `SOURCE_DATE_EPOCH` environment variable for reproducible builds

resolves #203 do not include current date if `:reproducible:` attribute is set

---

CHANGELOG.adoc
lib/asciidoctor-epub3/converter.rb
spec/fixtures/bibliography-xref/book.adoc
spec/fixtures/bibliography-xref/chapter.adoc
spec/fixtures/inline-anchor-xref/book.adoc
spec/fixtures/inline-anchor-xref/chapter.adoc
spec/xref_spec.rb

In particular, some cases were using `node.target` as the `id` instead
of `node.id`.

resolves #201 fix inline anchors missing their ids

---

CHANGELOG.adoc
lib/asciidoctor-epub3/converter.rb
spec/converter_spec.rb
spec/fixtures/author/book-multiple-authors.adoc
spec/fixtures/author/book-no-author.adoc
spec/fixtures/author/book-one-author.adoc
spec/fixtures/author/chapter.adoc

remove (for now) attributed creator links for books because Kindle can't handle them
closes #109

add support for multiple authors in book metadata

---

lib/asciidoctor-epub3/converter.rb
spec/fixtures/inline-quote/book.adoc
spec/fixtures/inline-quote/chapter.adoc
spec/inline_quoted_spec.rb

Based on [`Asciidoctor::Converter::Html5Converter`](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb).
* allowing wrapping with `<span>`
* allowing specifying id
* allowing specifying class via `role`

Include id and role for inline quoting

---

CHANGELOG.adoc
data/styles/epub3.css
lib/asciidoctor-epub3/converter.rb
spec/converter_spec.rb

This is the code I hacked together in an attempt to support the [horizontal] attribute for definition lists.  I'm not entirely satisfied with the result -- it turns out that horizonal lists weren't the best thing for my use case after I tried it, but others might find this useful.
This uses a table to layout horizontal lists, and the logic is adapted from the HTML layout backend.

resolves #165 add support for `[horizontal]` definition list

---

data/styles/epub3-css3-only.css

According to Wikipedia, Kindle Oasis has a definition of
1680 × 1264 pixels, 300 ppi. And according to #67, we can only detect
the model of kindle by its definition. We just apply the same recipe
as for PaperWhite here.
Please note that this PR was not tested on a real device, but was triggered by https://github.com/progit/progit2/issues/1438

Add darker font color recipe to kindle oasis too.

---

CHANGELOG.adoc
data/styles/epub3-css3-only.css
lib/asciidoctor-epub3/converter.rb
spec/converter_spec.rb

Center: what we have currently
Left: what was suggested in #125 
Right: what this PR does
While I personally like current visuals more, there are reasons in #123 why `<b>` is problematic.

resolves #123 remove <b> from chapter subtitle

---

CHANGELOG.adoc
README.adoc
asciidoctor-epub3.gemspec
lib/asciidoctor-epub3/converter.rb
spec/fixtures/inline-stem.adoc
spec/fixtures/inline-stem/book.adoc
spec/fixtures/stem.adoc
spec/fixtures/stem/book.adoc
spec/fixtures/stem/chapter.adoc
spec/inline_quoted_spec.rb
spec/stem_spec.rb

A quick screenshot of how [test stem document](https://github.com/asciidoctor/asciidoctor-epub3/blob/e1431f75c3b0d3f4ee7cdffd2830c68e6da7e211/spec/fixtures/stem.adoc) looks in Calibre:

resolves #10 add support for MathML

---

.github/workflows/ci.yml

Nokogiri 1.10.10 added precompiled Windows libs for Ruby 2.7

Enable CI on Ruby 2.7 on Windows

---

CHANGELOG.adoc
data/styles/color-palette.css
data/styles/epub3-css3-only.css
data/styles/epub3.css

This commit also removes Kindle-specific color adjustments so minor color changes are expected on Kindle

resolves #338 rescale color palette to use darker shades of gray

---

.github/workflows/ci.yml

See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

stop using deprecated `set-env` command in GitHub Actions

---

lib/asciidoctor-epub3/converter.rb
spec/fixtures/image-dimensions/chapter.adoc
spec/image_spec.rb

otherwise, use CSS style because HTML5 only allows pixels in width="..."
See https://www.w3.org/TR/2011/WD-html5-20110113/the-map-element.html#attr-dim-width
> The width and height attributes on img, iframe, embed, object, video, and, when their type attribute is in the Image Button state,
> input elements may be specified to give the dimensions of the visual content of the element (the width and height respectively,
> relative to the nominal direction of the output medium), in CSS pixels.
> The attributes, if specified, must have values that are valid non-negative integers.

resolves #382 use width attribute if image width is in pixels

---

docs/modules/ROOT/pages/index.adoc

I think the problem is that this attribute is used in the page title, and some places in the Antora pipeline don't support that use case unless the attribute is defined in the component descriptor. This is the best short-term fix.

define project-name attribute before document title to fix a warning in Asciidoctor 2

---

.github/workflows/ci.yml
CHANGELOG.adoc
Gemfile
asciidoctor-epub3.gemspec
lib/asciidoctor-epub3/converter.rb
spec/spec_helper.rb

This commit also drops support for Ruby < 2.4
This reverts commit 33e27eeb21fb62f1e82767f9957a0a03fa35c722.

resolves #363: reenable dependency on kindlegen gem

---

lib/asciidoctor-epub3/converter.rb

This is recommend by the XHTML spec. See https://www.w3.org/TR/xhtml11/conformance.html:
> XHTML document authors SHOULD use XML declarations in all their documents.
The "Send to Kindle" feature also seems to _require_ this XML declaration (otherwise non-ASCII characters in the HTML, like em dash and curly quotes, get mangled).
Also remove `<meta charset="UTF-8">` lines as those are now redundant.
This change works on the five different Android and Linux EPUB readers that I tested:
* Lithium
* Librera
* ReadEra
* Kindle (via both "Send to Kindle by E-mail" and the "Send to Kindle" share option from a file browser on Android itself)
* Calibre

Add XML declarations

---

data/styles/epub3.css

as discussed in
https://github.com/asciidoctor/asciidoctor-epub3/issues/422
i added user-select: none to i.conum.
older linux versions of calibre did not support this, but it has been fixed recently
this allows copying code examples from the ebook without the callouts.

resolves #422 add user-select:none to i.conum

---

lib/asciidoctor-epub3/converter.rb

Usually list items do not have extra roles (AsciiDoc does not allow roles in list items as per today), but they can be added via processors.
This PR honour the roles, and inject them into the generated list items.

feat: :sparkles: Honour roles for items in olists and ulists

---

lib/asciidoctor-epub3/converter.rb
spec/xref_spec.rb

Adds `id` attribute support to sidebar.
Fixes "Fragment identifier is not defined." error when trying to deep-link a sidebar. For example:
```
ERROR(RSC-012): foo.epub/EPUB/_chapter.xhtml(LINE,COLUMN): Fragment identifier is not defined.
```

fix sidebar deep link

---

data/styles/epub3-css3-only.scss
data/styles/epub3-fonts.scss
data/styles/epub3.scss

I came across *asciidoctor-epub3* some time ago and use it for my own projects. Back then I already noticed that the CSS files placed into the resulting \*.epub file were causing many warnings and errors in validators.
So, after using it for some years now, I finally got the time to fix all the issues. I verified my changes with the hardware I have at hand here (read:  Calibre 7.6.0 and my dusty Kobo GloHD with firmware version 3.19.5761 from December 2015). Both readers don't show any differences in the tests I did, but I can't cover all devices out there, of course.
There have been no changes in the semantics, just changes in the order of the individual CSS definitions.
I would kindly ask to review my changes and get them integrated at some point, but I also noticed that the files …

Sort definitions in SCSS files to make them pass validators

---

data/styles/epub3.scss

Rationale: for consistency with the HTML and PDF backends. Closes #494.

Make terms in description lists bolded rather than italicized

---

data/styles/epub3.scss

Rationale: see Amazon's [Image Guidelines - Reflowable](https://kdp.amazon.com/en_US/help/topic/G75V4YX5X8GRGXWV), item 2, "Quality of images", item c, "Images with captions". Closes #418.

Center caption text of block images
