README.adoc
Another minor documentation fix. 
See:
https://github.com/asciidoctor/asciidoctor-epub3/blob/master/lib/asciidoctor-epub3/packager.rb#L350-L354
=> Fixed documentation regarding uuid attribute

data/styles/epub3-css3-only.css, data/styles/epub3.css, lib/asciidoctor-epub3/converter.rb, lib/asciidoctor-epub3/packager.rb
- effectively enables monospace text
=> resolves #56 use built-in font names for mobi7

README.adoc
- document how to install the pre-release gem
- recommend using RVM
- minor revisions
=> resolves #38 document how to install the pre-release gem

lib/asciidoctor-epub3/converter.rb, lib/asciidoctor-epub3/spine_item_processor.rb
- set outfilesuffix correctly when converting content (chapter) files
- clean # from id attribute for xref
=> resolves #27 fix xref between chapter files

data/styles/epub3.css, lib/asciidoctor-epub3/converter.rb
- implement embedded handler to handle AsciiDoc table cell content
- add styles to strip leading margin for AsciiDoc table cell content
=> resolves #69 implement embedded to handle AsciiDoc table cell content

data/styles/epub3.css
As discussed in #72, the bitcoin symbol may cause confusion. Using the lightbulb icon is probably a better default.
Thanks in advance!
=> changed icon for TIP-admonition to lightbulb

lib/asciidoctor-epub3/converter.rb, lib/asciidoctor-epub3/packager.rb
- add additional TOC levels to toc nav in nav.xhtml file
- implement custom toc.ncx file to enable depth > 1
- move method to build TOC documents into Packager
- clean up arguments for add_* methods
- rework helper methods to sanitize XML
=> resolves #90 generate TOC levels based on toclevels attribute

lib/asciidoctor-epub3/packager.rb
- accept block image macro syntax in value of front-cover-image attribute
- don't crash if front cover image cannot be read
- use correct image on cover page
=> resolves #3 allow front-cover-image to be specified using block image macro

lib/asciidoctor-epub3/converter.rb
- warn when an xref cannot be resolved and text is provided
- warn for missing local anchors
- simplify ID of xref that links to chapter top
=> resolves #103 warn when xref cannot be resolved and text is provided

lib/asciidoctor-epub3/converter.rb
=> fix table frame and grid attributes

lib/asciidoctor-epub3/packager.rb
=> ttf mime-type

data/styles/epub3-css3-only.css
- detect Kindle Paperwhite using kf8 + resolution media query
- force darker colors on Kindle Paperwhite
=> resolves #67 use darker colors on Kindle Paperwhite

spec/cli_spec.rb, spec/spec_helper.rb, spec/xref_spec.rb
=> Introduce helper functions for tests

CHANGELOG.adoc, LICENSE.adoc, NOTICE.adoc, data/samples/asciidoctor-js-introduction.adoc, data/samples/sample-book.adoc, data/samples/sample-content.adoc, spec/cli_spec.rb
=> resolves #196 fix sample-book to be a valid book

CHANGELOG.adoc, data/styles/epub3.css, lib/asciidoctor-epub3/converter.rb
=> resolves #129 don't insert quotation marks around quotes

spec/cli_spec.rb, spec/spec_helper.rb
See https://github.com/asciidoctor/asciidoctor-epub3/issues/215#issuecomment-577681646
=> resolves #215 test that asciidoctor-epub3 respects --failure-level command-line option

lib/asciidoctor-epub3/converter.rb
The following list of methods are renamed to have `convert_` prefix. Old method calls would trigger deprecation messages.
- document
- embedded
- section
- preamble
- open
- abstract
- paragraph
- pass
- admonition
- example
- floating_title
- listing
- literal
- page_break
- thematic_break
- quote
- verse
- sidebar
- table
- colist
- dlist
- olist
- ulist
- image
- inline_anchor
- inline_break
- inline_button
- inline_callout
- inline_footnote
- inline_image
- inline_indexterm
- inline_kbd
- inline_menu
- inline_quoted
Fix #279
=> resolves #279 prefix node convert methods with convert_

lib/asciidoctor-epub3/converter.rb
=> eliminate 'ebook-chapter' attr

.github/workflows/ci.yml
setup-ruby does that for us automatically
=> stop installing Bundler on GH-Actions manually

docs/antora.yml
fix comment https://github.com/asciidoctor/asciidoctor-epub3/pull/459
=> remove patch level

CHANGELOG.adoc, lib/asciidoctor-epub3/converter.rb, spec/fixtures/image-in-table/book.adoc, spec/fixtures/image-in-table/circle.svg, spec/image_spec.rb
=> resolves #470 do not crash on an SVG image inside table cell

asciidoctor-epub3.gemspec
Reverts asciidoctor/asciidoctor-epub3#474
=> Revert "Ban gepub 1.0.16 to fix CI"

docs/modules/ROOT/pages/index.adoc
=> doc: add readk.it as e-book reader
